import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-relay-ghpm-'));
const dataRoot = path.join(root, 'data'); const transport = path.join(root, 'transport');
const repo = path.join(root, 'repo'); const origin = path.join(root, 'origin.git');
const state = path.join(root, 'state.json'); const audit = path.join(root, 'audit'); const project = 'BridgeDisposable';
fs.mkdirSync(dataRoot, { recursive: true }); fs.mkdirSync(transport, { recursive: true });
execFileSync('git', ['init', '--bare', origin], { stdio: 'ignore' }); fs.mkdirSync(repo);
execFileSync('git', ['-C', repo, 'init'], { stdio: 'ignore' });
execFileSync('git', ['-C', repo, 'config', 'user.name', 'test']); execFileSync('git', ['-C', repo, 'config', 'user.email', 'test@example.invalid']);
execFileSync('git', ['-C', repo, 'remote', 'add', 'origin', origin]); execFileSync('git', ['-C', repo, 'commit', '--allow-empty', '-m', 'base'], { stdio: 'ignore' });
const gt = await import('../dist/server/backend/goal-task.js'); const delivery = await import('../dist/server/backend/pm-delivery.js');
const cli = path.resolve('dist/server/github-pm/main.js');
const run = (...extra) => execFileSync(process.execPath, [cli, '--dataRoot', dataRoot, '--project', project, '--transport', 'local', '--transport-dir', transport, '--repo-dir', repo, '--pr', 'ju0o/Agent-Relay#5', '--state-file', state, '--audit-dir', audit, '--once', ...extra], { encoding: 'utf8' });
const comments = () => fs.readdirSync(transport).filter(n => /^\d+$/.test(n)).sort((a, b) => Number(a) - Number(b)).map(n => JSON.parse(fs.readFileSync(path.join(transport, n))));
const addComment = (body) => { const ids = comments().map(c => Number(c.id)); const id = String((ids.length ? Math.max(...ids) : 0) + 1); fs.writeFileSync(path.join(transport, id), JSON.stringify({ id, url: `local://${id}`, body })); return id; };
const goal = await gt.createGoal(dataRoot, project, { title: 'Bridge goal', goalStatement: 'Bridge goal statement' });
const task = await gt.createTask(dataRoot, project, { goalId: goal.goalId, title: 'Bridge task', goal: 'bounded goal', reason: 'bounded reason', scope: 'bounded scope', completionCriteria: ['result exists'], executionState: 'RESULT_RECEIVED', pmState: 'VERIFYING' });
const runId = 'bridge-run-1'; const runFolder = path.join(dataRoot, project, '2026-09-16', 'bridge-agent', '01'); fs.mkdirSync(runFolder, { recursive: true });
fs.writeFileSync(path.join(runFolder, 'meta.json'), JSON.stringify({ tags: [], runId })); fs.writeFileSync(path.join(runFolder, 'result.md'), 'verified result');
await gt.linkRunToTask(dataRoot, project, task.taskId, runFolder); await delivery.ensurePmDeliveryForTaskVerify(dataRoot, project, task.taskId);

console.log('1 exactly-one packet per pending Delivery'); run('--mode', 'export'); const packetFiles = () => fs.readdirSync(path.join(repo, 'pm-bridge/inbox')).filter(n => n.endsWith('.json')); assert.equal(packetFiles().length, 1);
console.log('2 duplicate poll/commit dedupe'); run('--mode', 'export'); assert.equal(packetFiles().length, 1);
const packet = JSON.parse(fs.readFileSync(path.join(repo, 'pm-bridge/inbox', packetFiles()[0]))); for (const key of ['schema_version','packet_id','project','task_id','run_id','delivery_id','created_at','bounded_context_hash','allowed_actions','canonical_state_summary','verification_context','evidence_refs','retry_lineage']) assert.ok(packet[key] !== undefined, key);
console.log('3 malformed and tampered judgment rejection'); addComment('PM_JUDGMENT v1\npacket_id: nope\ncontext_hash: nope\ndecision: ACCEPT\nretry: NONE\nreason: bad'); addComment(`PM_JUDGMENT v1\npacket_id: ${packet.packet_id}\ncontext_hash: ${'0'.repeat(64)}\ndecision: ACCEPT\nretry: NONE\nreason: tampered`); run('--mode', 'import'); const pmj = await import('../dist/server/backend/pm-judgment.js'); assert.equal(pmj.listPmJudgments(dataRoot, project).length, 0);
console.log('4 ACCEPT applies once and reconciles Delivery'); addComment(`PM_JUDGMENT v1\npacket_id: ${packet.packet_id}\ncontext_hash: ${packet.bounded_context_hash}\ndecision: ACCEPT\nretry: NONE\nreason: verified acceptance`); run('--mode', 'import'); assert.equal(pmj.listPmJudgments(dataRoot, project)[0].status, 'APPLIED'); assert.equal(delivery.getPmDelivery(dataRoot, project, packet.delivery_id).status, 'ACKNOWLEDGED'); assert.ok(comments().some(c => c.body.includes('PM_IMPORT v1')));
console.log('5 duplicate comment is not re-applied'); const before = pmj.listPmJudgments(dataRoot, project).length; addComment(`PM_JUDGMENT v1\npacket_id: ${packet.packet_id}\ncontext_hash: ${packet.bounded_context_hash}\ndecision: ACCEPT\nretry: NONE\nreason: verified acceptance`); run('--mode', 'import'); assert.equal(pmj.listPmJudgments(dataRoot, project).length, before);
console.log('6 allowlist and live-root boundary'); const marker = path.join(root, 'live-marker'); fs.writeFileSync(marker, 'marker'); const markerBefore = fs.readFileSync(marker, 'utf8'); run('--project', 'NotAllowlisted', '--mode', 'export'); assert.equal(fs.existsSync(path.join(dataRoot, 'NotAllowlisted')), false); assert.equal(fs.readFileSync(marker, 'utf8'), markerBefore);
console.log('7 restart state and audit durable'); assert.ok(fs.existsSync(state)); assert.ok(fs.existsSync(path.join(audit, 'pm-bridge.jsonl')));
console.log('PASS github-pm bridge disposable canonical assertions');
