import * as fs from 'node:fs';
import * as path from 'node:path';

export type RoleCapabilityFlags = { persistentSession: boolean; structuredInput: boolean; structuredOutput: boolean; readWorkspace: boolean; writeWorkspace: boolean; shell: boolean; subscriptionAuth: boolean; freeTier: boolean };
export type InputEnvelope = { kind: 'PM_BOOTSTRAP' | 'PM_FINAL_GATE' | 'PM_PREAMBLE' | 'QA_PACKET' | 'TASK_CONTRACT' | 'CHANGES'; schemaVersion: string; contractHash?: string; contextHash: string; body: string; attachments?: [] };
export type LiveSessionIdentity = { project: string; role: string; runtime: string; liveSessionIdentity: string };
export interface RoleRuntimeAdapter { readonly id: string; health(): Promise<{ ok: boolean; detail?: string }>; capabilities(): RoleCapabilityFlags; authMode(): { mode: 'oauth-subscription' | 'existing-plan-key' | 'free' | 'unknown'; provider?: string }; ensureSession(input: { roleId: string; project: string; sessionPolicy: 'persistent' | 'per-task'; sessionKey: string }): Promise<{ sessionId: string; created: boolean }>; send(sessionId: string, envelope: InputEnvelope): Promise<{ requestId: string }>; collect(sessionId: string, requestId: string, options: { timeoutMs: number }): Promise<{ text: string; structured?: unknown; raw?: unknown; tokens?: number; cost?: number }>; interrupt(sessionId: string): Promise<void>; abortSession?(sessionId: string): Promise<void>; resume(sessionId: string): Promise<{ ok: boolean }>; sessionIdentity(sessionId: string): { adapterId: string; sessionId: string; provider?: string; model?: string; identity?: LiveSessionIdentity }; }
export type RoleSession = { adapterId: string; sessionId: string; createdAt: string; lastUsedAt: string; preambleSent?: boolean; identity?: LiveSessionIdentity };
export function roleSessionPath(dataRoot: string, project: string, roleId: string): string { if (!project || /[\\/]/.test(project)) throw new Error('Invalid project: must be a safe name'); if (!roleId || /[\\/]/.test(roleId)) throw new Error('Invalid roleId: must be a safe name'); return path.join(dataRoot, '_relay', 'role-sessions', project, `${roleId}.json`); }
export function readRoleSession(dataRoot: string, project: string, roleId: string): RoleSession | null { try { return JSON.parse(fs.readFileSync(roleSessionPath(dataRoot, project, roleId), 'utf8')) as RoleSession; } catch { return null; } }
export function writeRoleSession(dataRoot: string, project: string, roleId: string, session: RoleSession): RoleSession { if (!session.adapterId) throw new Error('Invalid session.adapterId: required'); if (!session.sessionId) throw new Error('Invalid session.sessionId: required'); const file = roleSessionPath(dataRoot, project, roleId); fs.mkdirSync(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.tmp`; fs.writeFileSync(tmp, JSON.stringify(session, null, 2) + '\n'); fs.renameSync(tmp, file); return session; }
export async function ensureRoleSession(dataRoot: string, assignment: { roleId: string; runtimeAdapterId: string; workspace: { project: string }; sessionPolicy: 'persistent' | 'per-task' }, adapter: RoleRuntimeAdapter): Promise<RoleSession> { const existing = assignment.sessionPolicy === 'persistent' ? readRoleSession(dataRoot, assignment.workspace.project, assignment.roleId) : null; const result = existing && (await adapter.resume(existing.sessionId)).ok ? { sessionId: existing.sessionId, created: false } : await adapter.ensureSession({ roleId: assignment.roleId, project: assignment.workspace.project, sessionPolicy: assignment.sessionPolicy, sessionKey: `${assignment.workspace.project}:${assignment.roleId}` }); const now = new Date().toISOString(); const identity = adapter.sessionIdentity(result.sessionId).identity; return writeRoleSession(dataRoot, assignment.workspace.project, assignment.roleId, { adapterId: assignment.runtimeAdapterId, sessionId: result.sessionId, createdAt: existing?.createdAt ?? now, lastUsedAt: now, ...(identity ? { identity } : {}) }); }
